### ISSUE TITLE
Not Accepting Matching Barcodes

### ISSUE THREAD

**Issue by mrajayp** [crononauta/tally-ho#11]
At intake barcodes are entered and they should match, however the system rejects them as mismatching. 

![image](https://cloud.githubusercontent.com/assets/6093960/3278136/a9747d2e-f3a8-11e3-8f10-85db7b97e2fc.png)

**Comment by jmarente** [comment]
The problem is that the barcode exceeds nine digit and this is not allowed, but currently does not exist a specific message for this type of error.

**Comment by mrajayp** [comment]
Can we push a change on this soon? Basically we are not able to do any
useful testing without this working.

Best,

Ajay

On Mon, Jun 16, 2014 at 10:48 AM, jmarente notifications@github.com wrote:

> The problem is that the barcode exceeds nine digit and this is not
> allowed, but currently does not exist a specific message for this type of
> error.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/crononauta/tally-ho/issues/11#issuecomment-46154372.

## 

_Ajay Patel_

_Voter Registration and ICT Advisor_

_UNSMIL Electoral Support Team_

_Phone (Libya): +218 917 127 082_

_Phone (US): +1 917 306 7896_

_Email: mrajayp@gmail.com mrajayp@gmail.com_

**Comment by FPerezP** [comment]
This bug has been added to Redmine: https://redmine01.scytl.net/issues/83717
