### ISSUE TITLE
Change + Review Request - Audit Triggers

### ISSUE THREAD

**Issue by mrajayp** [crononauta/tally-ho#12]
Currently there are two audit triggers. Trigger 1 needs to be adjusted accordingly. Trigger 2 needs to be reviewed and potentially adjusted: 

i)  Trigger 1 – To guard against over-voting: The number of ballots reported to be used in a station exceeds the number of potential voters – 90 percent of the number of registrants + 10 persons to accommodate staff and security.

(with “number of ballots reported to be used”  being a system calculation of the sum of number of cancelled ballots, number of unstamped ballots, number of invalid votes, and the sum of the valid cast votes from the results form)

**_Currently this is set against the number of registrants + 10 persons. We want to strengthen this check.**_

ii) Trigger 2 – To guard against errors and tampering with the form: The sum of the results section of the form fails to be equal to number of ballots expected based on the calculation of the key fields from the reconciliation section 

(with ‘the number of ballots expected’ to be the number of ballots found inside the ballot box minus the number of unstamped ballots and the number of invalid votes), with a 3% tolerance applied.

*\* We need to check that this set at 3%...there is some confusion as to where we left it last**

**Comment by FPerezP** [comment]
This issue has been added to Redmine: https://redmine01.scytl.net/issues/83857
