### ISSUE TITLE
Form Bar Code Ballot Number and Centre Number Link Check Not Running

### ISSUE THREAD

**Issue by mrajayp** [crononauta/tally-ho#14]
There is a problem with the way the system is handling and restricting the entry of forms. 

Each form has a ballot number assigned - this is read by the computer though the entry of the bar code. Form is printed with the barcode and the candidates. 

All forms have barcodes and ballot numbers assigned. Some forms have centres and stations also assigned. Where centers and stations are not assigned, the staff will have to assign the centre and station depending upon what in written on the form. 

There should be a check to ensure that that people are not assigning a centre to a barcodes which do not match. ie if a barcodes relates to ballot number 10 while the centre relates to 20. This was prevented previously, however it seems to not work any longer. 

You can see from the below this centre and the barcodes assigned should not match.

![image](https://cloud.githubusercontent.com/assets/6093960/3299726/ae8ed4ce-f616-11e3-81cc-8890691d8cf9.png)

![image](https://cloud.githubusercontent.com/assets/6093960/3299813/6ea458aa-f618-11e3-95d1-2d48b63ca103.png)

**Comment by FPerezP** [comment]
This bug has been added to Redmine: https://redmine01.scytl.net/issues/83939
