### ISSUE TITLE
Section 5.1.2.5 - Quality Control and Archiving workflow

### ISSUE THREAD

**Issue by dcasasmol** [crononauta/tally-ho#3]
Currently, the app has Quality Control and Audit workflow in 2 separated steps. Do we have to unify them in just one step?

**Comment by dcasasmol** [comment]
This question has been answered via email:
"i.  A Quality Control check will be conducted of all forms that have been successfully entered into the system until this point. Forms will be reviewed against their corresponding entry in the database, as entered by the data clerks.

ii.  Archiving will verify that each results form has passed through all the required stages listed above and will automatically run the results against the audit test – as detailed in section “Audit Review”.

iii.  Forms will be distributed to the data entry clerk’s in-trays by the section supervisor.

iv.  The data entry clerks will double enter barcode number and check the centre name, polling centre code and polling station. The clerks will then proceed.

v.  Clerks will review each form and accept or reject the form if the entry in the database does not match the form. Rejected forms will be forwarded to the Data Entry One Station for re-entering into the system.

vi.  If a form is accepted the system will automatically pass it though the audit test.

vii.  If the form passes the audit tests, the system will accept the data from the form. The archive station will print a cover with the non-sensitive details and staple to the front of the form. The form will be filed by voting district and polling centre/station for safe storage.

viii.  Forms failing the audit tests will be marked as under audit in the database. The archive station will print a cover highlighting the issue and the sheet will be moved to the audit holding area for review by the Audit Team."

**Comment by dcasasmol** [comment]
I understand the Quality Control and Archiving workflow, but I am not sure if we should have two separate steps or just one.

Thanks.

**Comment by mrajayp** [comment]
I believe as one step, as in, the user reviews, then if it is correct - selects correct. As such the process will then proceed as audit post the submission of the form. 

Does that make sense?

**Comment by dcasasmol** [comment]
It seems to me fine change the current implementation to do it in one step (just a link on the administration's dashboard).

There is a user type for each of the actions (quality-clerk, file-clerk) besides archive-supervisor, so perhaps we should eliminate one of the two clerk users and allow the other to do both actions.

What do you think?

**Comment by mrajayp** [comment]
So this would be done by the audit clerks, not audit supervisors. 

But yes, we need to abolish one user types/merge them...

**Comment by FPerezP** [comment]
Hi Ajay,
The problem is, at this moment, that every user type just do one action. When a user logs in goes to the screen to do just that action, with no menu or options list. So, merging user types makes that when a user with two possible actions to do logs in, the app doesn't know to which screen has to redirect. We have to add a new screen where the user can select which action it wants to do, is it ok for you?

**Comment by FPerezP** [comment]
This issue has been added to Redmine: https://redmine01.scytl.net/issues/83780
