### ISSUE TITLE
Section 5.7 - What reports are not implemented yet?

### ISSUE THREAD

**Issue by jmarente** [crononauta/tally-ho#4]
Currently, there are several reports in the application. But not all of them have the option to be exported as CSV. Below, it's shown the list of reports expected and posible equivalences found in the application:
- Progress of the tally progress: Report Offices and From Progress (Not CSV)
- General statistics on the election: Races Progress Report (Not CSV)
- Station races have not been in-take: Races Progress Report (Not CSV)
- Turnout and results of each race: Candidates Votes (Only CSV)

We're not sure if this equivalences are correct. In case any of them are not, What information should be shown and format?.

Some of them are just shown as table views, Should be exported as CSV too?.

Thank you.

**Comment by mrajayp** [comment]
To be honest, we don't really need these in CSV for now. It would be useful but not essential. We will wish to consider later the breadth of reports though. 

As for results in not csv, we are interested in this too, however it was not under the deliverables for phase 1. I would be keen to see how far we get in this cycle before exploring this too far. We use these CSVs to import into some external systems - for presenting the results outside of the tally centre.
