### ISSUE TITLE
About implementation: Use session info to check form id

### ISSUE THREAD

**Issue by dcasasmol** [crononauta/tally-ho#5]
Currently, most of controllers of the application follow this workflow.
1. When we are working with a form and we need to send the form id to the next controller, for example, a confirmation view, we store the id in session.
2. In the next view, we check that the stored form id matchs with the form id got by post.

This can be a problem because if we work with multiple tabs in the browser, the session variable will be overwritten with differents identifiers, and we will get an error when we should not.

It is not ok to use the session to obtain or check this data.

**Comment by mrajayp** [comment]
I can see how that would be an issue. I would note, I don't think we had a problem last time, however it is possible without us knowing...

How would you suggest we resolve this?

**Comment by FPerezP** [comment]
This bug has been added to Github: https://redmine01.scytl.net/issues/83489
