### ISSUE TITLE
Section 5.13 - Audit pending and clearance pending states

### ISSUE THREAD

**Issue by jmarente** [crononauta/tally-ho#7]
When a form is moved to the new states Audit Pending State or Clearance Pending State. What operations could be done with forms in these states?

**Comment by mrajayp** [comment]
These forms should open for data entry 1.

**Comment by jmarente** [comment]
In clearance, there could be forms without center nor station assigned, so if these form are passed from Clearance to Clearance Pending State, they won't be able to be open in data entry 1, since they don't have center or station. We will move these form to Unsubmitted.

Another question:
What is the meaning of "or a new form from the field" in section 5.13? What option in clearence/audit form have to be selected for this case?

**Comment by mrajayp** [comment]
Ok that sounds reasonable. 

As for the 'or new form from the field' it is possible  we will not request an audit, but ask the field to send us a copy. To be honest, I can't remember the dropdowns on these pages. I can check tomorrow, or if you can post them that would be great.

**Comment by jmarente** [comment]
The options available in 'Action prior to recommendation' are:
- Request copy from field
- Request Audit Action from field
- Pending Advice
- None Required

So these two new states will be applied if one of the two first option are selected.

**Comment by mrajayp** [comment]
Request a copy from the field would count for requesting a new form.
