### ISSUE TITLE
Additional Requirement: Candidates deactivation interface and changes in results reports

### ISSUE THREAD

**Issue by mrajayp** [crononauta/tally-ho#9]
A new issue has been identified with regards to the tabulation process. In order for the election to take place on time, the legislation has been updated to allow contests about the eligibility of candidates which will only be resolved after polling. 

As such, while candidates will be on the ballot and will be on the screen, they may not be in the results if a decision is taken to remove them. 

Further, a decision may be later revoked and the candidates returned to the results. 

As such data entered into the system needs to be preserved as entered. However the following are required: 
- A way to mark candidates as active or inactive. 
- If a candidates is marked as either inactive or active, their names will show up throughout the data entry process (as they remain on the ballot). 
- In the csv report which shows votes per candidate (form_results csv):
       - there will be an additional column that marks if a candidate is active or deactivated
- In the csv report which shows results by race (candidates_votes csv),
      - deactivated candidates will be shown
      - votes for deactivated candidates will be shown as <disabled> (still needs to be confirmed on this end) 
  -  An additional column is required for total voters for candidates. The votes assigned to deactivated candidates will show up in this total (still needs to be confirmed on this end)

**Comment by FPerezP** [comment]
This requirement has been added to Redmine: https://redmine01.scytl.net/issues/83868
